Title = "Furbuild"
BaseUrl = "http://furbuild.com/"
LanguageCode = "en-gb"
Paginate = 5
Copyright = "All rights reserved - 2015"
Canonifyurls = true
Theme = "casper"

[params]
  description = "Building our own fursuits"
  cover = "images/foam-ears-front-profile.jpg"
  hideHUGOSupport = true
  googleAnalyticsUserID = "UA-73425660-1"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Zee"
  weight = -110
  pre = "<h6 style='padding-top:1em;'>Characters</h6>"
  identifier = "zee"
  url = "/character/zee"

[[menu.main]]
  name = "Caraid"
  weight = -100
  identifier = "caraid"
  url = "/character/caraid"